### ISSUE TITLE
"Open profile in OSMCha.org" button does not work when user has spaces in name

### ISSUE THREAD

**Issue by elevenchars** [deevroman/better-osm-org#131]
Clicking the button on the user profile does not generate the correct OSMCha filter. As an example, [this profile](https://www.openstreetmap.org/user/Eduard%20Schindler) generates an OSMCha filter link with `%2520` instead of `%20`. Manually correcting the escaped `%` in the URL fixes this issue.

**Comment by deevroman** [comment]
Fixed in next version. Thanks!

**Comment by evgenykatyshev** [comment]
Is non-latin letter also fixed?
