### ISSUE TITLE
Links to osmcha and similar

### ISSUE THREAD

**Issue by Martinligabue** [deevroman/better-osm-org#20]
while looking at a changeset some links to osmcha and similar changeset helpers would be nice. for osmcha it would be similar to function addRevertButton(), but the link would be https://osmcha.org/changesets/${changeset_id}

**Comment by deevroman** [comment]
Maybe I'll add this, but for now it's better to use this extension: https://addons.mozilla.org/ru/firefox/addon/jumptoosmchangesetanalyzer/

**Comment by Martinligabue** [comment]
thanks for the other extension, I think that it would be nice if it were added to this one, as it's easier to install just one good extension than multiple, that might be incompatible or draw one on top of the other

**Comment by deevroman** [comment]
This makes sense, but this extension doesn't change the site page: just an icon in the address bar or extension panel.

**Comment by karakartala** [comment]
> This makes sense, but this extension doesn't change the site page: just an icon in the address bar or extension panel.

@deevroman Have you changed your mind? Will you add it? It would be nice if this feature was added.

**Comment by deevroman** [comment]
![изображение](https://github.com/user-attachments/assets/ac7e8c1c-5d40-4073-b9dc-ac96bbca7c0e)

<img width="759" alt="Снимок экрана 2024-08-15 в 21 38 55" src="https://github.com/user-attachments/assets/53b12e54-7e3a-454d-aeed-6c2972591a3a">

But seriously, I'll try adding it in the next release (probably disabled by default, because I still don't have a good idea where to add it in the interface)

**Comment by deevroman** [comment]
I do not know when I will be able to release the release (there are too many shoals in the visualization of chagesets), but you can try the dev version https://github.com/deevroman/better-osm-org/raw/dev/better-osm-org.user.js

<img width="483" src="https://github.com/user-attachments/assets/b5b5c6d0-2940-48ae-b2b0-1eb23d9712ab">

**Comment by karakartala** [comment]
> I do not know when I will be able to release the release (there are too many issues in the visualization of changesets), but you can try the dev version https://github.com/deevroman/better-osm-org/raw/dev/better-osm-org.user.js
> 
> <img alt="" width="483" src="https://private-user-images.githubusercontent.com/25708359/358936028-b5b5c6d0-2940-48ae-b2b0-1eb23d9712ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MzY2ODMsIm5iZiI6MTcyNDUzNjM4MywicGF0aCI6Ii8yNTcwODM1OS8zNTg5MzYwMjgtYjViNWM2ZDAtMjk0MC00OGFlLWIyYjAtMWViMjNkOTcxMmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI0VDIxNTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxOTBiMmI1ZjBhZDc3ZTUyNmFmM2E3ZDNhMzY4YjMxZWY4OTYzZjQ4NTBkNDEzNTBjNDExZTUxOTA4MDg2MGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lAtCo1VxGW4V_oJ2xmVICpr_kbcGoudE7Rtb0hes-uc">

It is very nice. Thank you very much.

**Comment by deevroman** [comment]
done in 0.4.9 (Viewing changesets has also been added, but is disabled by default in the settings)
