### ISSUE TITLE
Keeping notes open between edit/nonedit mode

### ISSUE THREAD

**Issue by Martinligabue** [deevroman/better-osm-org#56]
As per title, when entering edit mode with notes layer on, it should enable them in the editor too, as usually you might want to edit more notes than a single one

**Comment by deevroman** [comment]
hmm, I thought one of the latest iD releases fixed this problem. But apparently it only works if you select some note.

**Comment by Martinligabue** [comment]
it keeps the note open, not the note layer though

**Comment by deevroman** [comment]
Strangely, in Firefox, I have all the notes on the map displayed

**Comment by Martinligabue** [comment]
I'm in firefox too, just tested, but with the overlay in view, it's not enabled in edit, weird

**Comment by deevroman** [comment]
To avoid misunderstandings, I talk about this usage:

https://github.com/user-attachments/assets/241e7ddf-21cd-4f33-b784-202970c3122e

If this doesn't work for you, it's best to let the developers know osm.org.

---

Enabling the notes layer in iD even without the selected note on the osm.org, prevents this https://github.com/openstreetmap/iD/pull/8042

Right now, I specifically avoid any interference with iD: iD is much more complex and easier to break/degrade performance

**Comment by Martinligabue** [comment]
I see, I see that the pr is still open, I think im on the stable id, but that's how I thought of it, so probably I just have to wait for it to reach stable? in any case I see that this is not the best place, I'll open the issue in id if that will be a problem, for now this one is not needed, thanks a lot

**Comment by deevroman** [comment]
Please note that on the right there is a list of issues related to this PR
<img width="317" alt="Снимок экрана 2024-10-23 в 02 07 52" src="https://github.com/user-attachments/assets/6335d974-b87e-4401-9816-357d5a15a772">

**Comment by Martinligabue** [comment]
thanks, I'll follow them and see if I can add something useful
