### ISSUE TITLE
Show "blocked user" badge on more places

### ISSUE THREAD

**Issue by Dimitar5555** [deevroman/better-osm-org#59]
Looking at https://www.openstreetmap.org/history#map=11/43.5187/28.4591 we see that the user is blocked.
![image](https://github.com/user-attachments/assets/f7f2628b-57c5-4a3a-826d-1e307e830265)

But if we come directly to a user's changeset, there is no "blocked user" badge near his username.
https://www.openstreetmap.org/changeset/158551016
![image](https://github.com/user-attachments/assets/d68b74c4-1dd5-414c-ae75-8b75e026a596)

Also on their profile there is an active block link but it is very easy to skip it. A "blocked user" badge would be very helpful.
https://www.openstreetmap.org/user/Vik_M
![image](https://github.com/user-attachments/assets/f205889a-ede7-4309-b0ea-20fb915c919e)

**Comment by deevroman** [comment]
done in 0.5.2

I also made highlighting users in comments to edits.

<img width="403" src="https://github.com/user-attachments/assets/c6283db8-4f6f-403c-8c2e-d2ab73640fd8">

<img width="784" src="https://github.com/user-attachments/assets/7118cc83-783e-443b-bfef-0cd06948d495">
