### ISSUE TITLE
OSMCha Like/Dislike buttons display issue

### ISSUE THREAD

**Issue by mutipg** [deevroman/better-osm-org#74]
In changeset page there are 2 buttons to OSMCha Like+Unlike, but it doesn't look correct on my computer:
![image](https://github.com/user-attachments/assets/f2b89888-0438-4832-87e2-03a0a439531b)

They could have also other titles if images aren't showing - instead of 'OSMCha review like' it could be 'OSMCha like' + 'OSMCha dislike'

**Comment by deevroman** [comment]
What browser and its version? Also, are you using Tampermonkey or Violentmonkey?

**Comment by mutipg** [comment]
I'm using newest Opera with Violentmonkey.

**Comment by mutipg** [comment]
I think that are an errors from console to OSMCha buttons (img src are the same):

> /changeset/159163715:1 Refused to load the image 'blob:https://www.openstreetmap.org/d8f0cbd2-837d-40f9-b201-7a228f7c6fda' because it violates the following Content Security Policy directive: "img-src 'self' data: www.gravatar.com *.wp.com tile.openstreetmap.org gps.tile.openstreetmap.org *.tile.thunderforest.com tile.tracestrack.com *.openstreetmap.fr matomo.openstreetmap.org https://openstreetmap-user-avatars.s3.dualstack.eu-west-1.amazonaws.com https://openstreetmap-gps-images.s3.dualstack.eu-west-1.amazonaws.com".

> /changeset/159163715:1 Refused to load the image 'blob:https://www.openstreetmap.org/d8f0cbd2-837d-40f9-b201-7a228f7c6fda' because it violates the following Content Security Policy directive: "img-src 'self' data: www.gravatar.com *.wp.com tile.openstreetmap.org gps.tile.openstreetmap.org *.tile.thunderforest.com tile.tracestrack.com *.openstreetmap.fr matomo.openstreetmap.org https://openstreetmap-user-avatars.s3.dualstack.eu-west-1.amazonaws.com https://openstreetmap-gps-images.s3.dualstack.eu-west-1.amazonaws.com".

> /changeset/159163715:1 Refused to load the image 'blob:https://www.openstreetmap.org/d8f0cbd2-837d-40f9-b201-7a228f7c6fda' because it violates the following Content Security Policy directive: "img-src 'self' data: www.gravatar.com *.wp.com tile.openstreetmap.org gps.tile.openstreetmap.org *.tile.thunderforest.com tile.tracestrack.com *.openstreetmap.fr matomo.openstreetmap.org https://openstreetmap-user-avatars.s3.dualstack.eu-west-1.amazonaws.com https://openstreetmap-gps-images.s3.dualstack.eu-west-1.amazonaws.com".

![image](https://github.com/user-attachments/assets/852d7147-9465-450d-a975-1546de81867b)

**Comment by deevroman** [comment]
Reproduced in Google Chrome. I'll try to fix it soon

**Comment by deevroman** [comment]
fixed in 0.5.4. Thanks for the report!

https://raw.githubusercontent.com/deevroman/better-osm-org/master/better-osm-org.user.js
