### ISSUE TITLE
OSMCha 'Like+Dislike' icons in colors instead of gray

### ISSUE THREAD

**Issue by mutipg** [deevroman/better-osm-org#78]
The OSMCha 'Like+Dislike' icons look correct now. They are both currently grey. Is it possible to make 'Like' green and 'Dislike' red?
![image](https://github.com/user-attachments/assets/d2e26dc3-ce00-408d-aeaa-3b81b03ad569)

Mój system:
Opera: 114.0.5282.185
Violentmonkey: v2.28.0

**Comment by deevroman** [comment]
The grey colour is chosen on purpose so as not to be distracting and to show that the likes/dislikes are not set. When you click on them, they will become coloured.

p.s. Just remember to open OSMCha.org at least once for the extension to get the token

**Comment by mutipg** [comment]
Thanks, it actually works fine :) So I'm closing this issue.
