### ISSUE TITLE
The script is applied twice in iD

### ISSUE THREAD

**Issue by Nekzuris** [deevroman/better-osm-org#80]
On https://www.openstreetmap.org/edit the script is applied twice and opens two settings windows on top of each other.

![image](https://github.com/user-attachments/assets/fd586744-dba4-437c-8b5e-1c7853f1724c)

**Comment by deevroman** [comment]
Note to self: the settings are opened if *.openstreetmap.org embedded as an iframe on other sites

![изображение](https://github.com/user-attachments/assets/556f9dbd-ba66-4542-9d75-d1f8dbc2a0d2)

**Comment by deevroman** [comment]
will be fixed in the next update
