### ISSUE TITLE
Unchanged value highlighted in yellow

### ISSUE THREAD

**Issue by ivanbranco** [deevroman/better-osm-org#9]
In my understandanding, while browsing history, green values are the new values and yellow values are edited values. Here tho: https://www.openstreetmap.org/node/5611154617/history
Wikidata is yellow even if the value wasn't changed (as can be seen in the "was: qitem" window):
![image](https://github.com/deevroman/better-osm-org/assets/94002623/4d6e4e17-c55f-446d-86f2-ea4b5aaaf927)

Maybe it's in conflict with this other script I have? https://github.com/ZeLonewolf/osm-wikidata-greasemonkey

**Comment by deevroman** [comment]
Thanks, fixed! I also found and fixed a crash when working with this extension.
