### ISSUE TITLE
Seems to break back behavior

### ISSUE THREAD

**Issue by thibaultmol** [deevroman/better-osm-org#91]
i've noticed that in firefox, if I open History, click on a changeset and try to go back using keyboard shortcut (ALT + left arrow). it doesn't work.
it's supposed to do the same as the back button

**Comment by deevroman** [comment]
As a quick fix, you can edit the script by removing `e.code === "ArrowLeft" || ` and `e.code === "ArrowRight" ||`

<img width="552" alt="Снимок экрана 2024-12-04 в 23 40 46" src="https://github.com/user-attachments/assets/63d5a502-6825-40c7-96d0-c8f0d43fbece">
